### ISSUE TITLE
Browser annotation per test method

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/neodymium-library#10]
The browser annotation @Browser should be per method or per class. In case a method has one, it should supersede the class definition.

**Comment by occupant23** [comment]
The current implementation works as expected but I would like to adjust the interface.

It would be nice to implement the Browser annotation analog to the DataSet Annotation:
- @Browser
- @Browsers
- @SuppressBrowser

Please adjust the documentation accordingly.

**Comment by occupant23** [comment]
Please rename @SuppressBrowser to @SuppressBrowsers

**Comment by marcuskaufmann** [comment]
all done

**Comment by occupant23** [comment]
rechecked works now as described and with the new annotation style.
