### ISSUE TITLE
Keep browser open / on failure as annotation

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#103]
Currently this feature is only available via configuration. It can be quite handy to manipulate this within the code without changing configuration files.

**Comment by occupant23** [comment]
This could actually two separate annotations:
* `@KeepBrowserOpen`
* `@KeepBrowserOpenOnFailure`
or 
* `@KeepBrowserOpen(boolean onlyOnFailure)` with `onlyOnFailure` default set as `false`.

The same logic as for the standard features apply (see https://github.com/Xceptance/neodymium-library/wiki/Neodymium-configuration-properties#browser-behavior-configuration). I think it isn't stated that the browser needs to be in non headless mode.

**Comment by georgkunze** [comment]
Documentation is done in the "KeepBrowserOpen-Annotation" branch in the wiki-project.
