### ISSUE TITLE
Parse a specific path/key as DataObject

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#104]
It would be good to add the possibility to convert a specific key into a given DataObject (POJO). This is required due to the fact that it is often not feasible to describe the whole test data as on DataObject.

**Comment by occupant23** [comment]
feature ready for test documentation is already done

**Comment by occupant23** [comment]
@jseng92: please test

**Comment by jseng92** [comment]
a link to "What is JsonPath" in the documentation might be uselful 

at: neodymium-library -> Wiki -> Test data provider -> Complex test data objects

**Comment by jseng92** [comment]
missing Method at TestCompoundClass in the documentation 

method: getDescription()

**Comment by h-arlt** [comment]
IMO JavaDoc of new method is way too unspecific.

It should be more like:
_Retrieves an element from the JSON representation of current test data using the given JsonPath expression and in case such an element was found, it will be returned as instance of the given class, filled with appropriate values._

**Comment by occupant23** [comment]
refactured code and adjusted documentation. Please retest

**Comment by h-arlt** [comment]
looks good to me
