### ISSUE TITLE
Support ShadowDOM

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#113]
WebComponents will become more important within the future.

We already found out that Selenide will have a basic support for ShadowDom starting with version 5.10.0 (They will currently support Chrome and Firefox)

**Comment by occupant23** [comment]
We are currently in contact with the Selenide dev team and check if their API will fit our needs.

**Comment by occupant23** [comment]
Create a wiki page to describe the usage of the future Selenide feature.

```Java
String shadowHost  = "#shadow-host";

SelenideElement button =  $(shadowCss("#myButton", shadowHost)).click();
button.shouldHave(text("Changed text"));

SelenideElement input =  $(shadowCss("#myButton", shadowHost));
input.shouldHave(attribute(“placeholder”, ”Fill me"));
```

**Comment by occupant23** [comment]
### Next steps:
- Create a new project on GitGub (tell @rschwietzke what you need)
- Build it up from ground up using the neodymium-template
- Create tests against a website using shadow dom (e.g. https://javascript.info/shadow-dom)
- Use the new Selenide (5.10.0) shadow dom feature and build up an example test like above to showcase the usage

**Comment by georgkunze** [comment]
@occupant23 Is this finished? Can we close it?
