### ISSUE TITLE
Improve local proxy implementation

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#117]
### Improvement
- [x] instead of trusting all servers it would be better to create a root certificate on the fly use the following approach: https://github.com/browserup/browserup-proxy/issues/137#issuecomment-535509225
  - add another property to decide which way should be used (Default: create a certificate on the fly)

### Testing 
- [x] add tests that verify the own code
  - [x] validate that the usage of properties leads to the correct behavior e.g. certificate are required
  - [x] validate that the RuntimeExceptions are thron correctly
  - [x] validate that the proxy is working (don't test the whole functionality) by using a basic function e.g. basic auth

### Documentation
- [ ] add a new wiki page that describes the local proxy API
- [ ] use the page above to explain especially the basic auth via the local proxy
  - [ ] currently usage in Chrome is recommended since you are able to ignore certificate errors if you pass the following argument `browserprofile.CHROMEPROFILENAME.arguments = -ignore-certificate-errors`. FF is running but shows an SSL exception
- [ ] use and link the showcase https://github.com/Xceptance/neodymium-showcase/issues/13

**Comment by occupant23** [comment]
@oomelianchuk: Please review and test the implementation above.

**Comment by h-arlt** [comment]
Feature works as expected. Some small code improvements added as comments.

Q: In case the root CA cert file already exists, should Neodymium check if the cert is still valid?
Q: Should the root CA cert file be automatically removed at VM exit?
Q: Will the documentation tasks be handled in a separate issue?

**Comment by occupant23** [comment]
will do Q2, this solves Q1 automatically
Q3 will be done within the release process

**Comment by occupant23** [comment]
documentation of the settings is done
