### ISSUE TITLE
Support global browser settings

### ISSUE THREAD

**Issue by ckeiner** [Xceptance/neodymium-library#123]
Currently, I have to manually set my browser settings for each browser configuration. While this often helps, it can also become tedious if I want to set the same value for each browser configuration. This often happens for the headless mode which I always want to stay the same for each browser.

It would really help if I had some way to set the same value for all browser configurations, either via a global browser configuration which get overwritten by specific ones or by being able to refer to another property, e.g.
```
browser.headless = true
browser.<config>.headless = browser.headless
```

**Comment by occupant23** [comment]
code and documentation ready for test

**Comment by oomelianchuk** [comment]
IMO the changes are good, I have nothing to complain about

**Comment by occupant23** [comment]
@ckeiner Please have a look if this suits your needs.

**Comment by ckeiner** [comment]
* Global Settings:
    * There may be limited use cases for such cases, but `browserResolution`and `screenResolution` should also be configurable globally.
    * IMO, even `arguments` might be valid global settings if you do not plan to mix different browsers.


* Wiki Documentation
    * Did you happen to switch the possible values of `pageLoadStrategy` with the ones from `acceptInsecureCerts`?
        * If not, what does each value mean?
* Documentation of the `browser.properties`:
    * What is `<short name>` and what are non-special values (i.e. everything besides "global")?
    * Why is it named `<short name>` and not `<configuration tag>` like it is in the wiki documentation?
    * A sample for a global browser profile would be good, even if it is commented out.

**Comment by ckeiner** [comment]
See https://github.com/Xceptance/neodymium-library/commit/21e74a43582c5cc2dd0fb45941e486c0146e638f#r43402070
As well as https://github.com/Xceptance/neodymium-library/commit/21e74a43582c5cc2dd0fb45941e486c0146e638f#r43402047

**Comment by occupant23** [comment]
Global Settings:
* Added browserResolution.
* Wont add: screenResolution (is only relevant for test environments)
* Wont add: arguments (they are specific to the used browser and this could cause errors that would be hard to find)

Wiki Documentation: fixed it

Documentation of the browser.properties: fixed it

**Comment by occupant23** [comment]
Can be rechecked again.

**Comment by ckeiner** [comment]
Except a minor grammatical error (https://github.com/Xceptance/neodymium-library/commit/4f998b50bddc215a18d10d7b5a97f30ed7824aaa#r43434237) which was in before, everything looks fine to me.

**Comment by occupant23** [comment]
done :-)
