### ISSUE TITLE
Introduce reuse counter for web driver/browser instances

### ISSUE THREAD

**Issue by jowerner** [Xceptance/neodymium-library#124]
Reusing browser instances for multiple tests is great as it can save a lot of test time. However, observations have shown that some browsers may get fatter and slower over time or even crash sporadically when being reused for many test cases. In these situations, a configurable reuse counter could help which controls how often a certain driver/browser instance is used before it is recreated freshly.

**Comment by occupant23** [comment]
@h-arlt Please recheck.

**Comment by h-arlt** [comment]
Besides two small improvements regarding documentation, code looks good to me and works as expected.

**Comment by h-arlt** [comment]
Well done my friend ;-)

**Comment by occupant23** [comment]
documentation for configuration and base functions done
