### ISSUE TITLE
Fix an error in SelenideAddonsTest

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#125]
There is an error due to an GDPR overlay. 

Solution: Cancel the dialog before interacting with the site itself.

**Comment by occupant23** [comment]
@oomelianchuk Please review and test.

**Comment by oomelianchuk** [comment]
added `Selenide.refresh()` after closing the cookie dialog to make tests more stable. Few repetitive local test runs have proved, that presence of `Selenide.refresh()` at this place improves the test stability.
