### ISSUE TITLE
JUnit categories

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#13]
Add JUnit categories support to group tests. Consider Maven parameter that constain the tests that will be executed. Also provide an commandline override switch.

**Comment by occupant23** [comment]
add documentation how to use certain browsers with certain tags (test case level) via jenkins(maven console)

**Comment by marcuskaufmann** [comment]
Surprisingly this features works out of the box. It only works for tests executed via maven, but that is probably the only use case for executing a test subset. There is no IDE support at the moment since it is a feature that is 100% realized by maven itself.
Described here: https://github.com/junit-team/junit4/wiki/categories#using-categories-with-maven

Suite classes are not required. Just mark test classes or methods with the appropriate category and define the groups in the pom that you want to execute during test phase.
