### ISSUE TITLE
Remove Guava dependency

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#131]
The guava dependency: com.google.guava is only used in one place and this code can easily replaced by using streams.

**Comment by occupant23** [comment]
@oomelianchuk Please recheck.

**Comment by h-arlt** [comment]
Unfortunately, Guava is not completely gone. It is still a transitive dependency of `browserup-proxy-core`.

**Comment by occupant23** [comment]
That's okay. I just wanted to remove the explicit dependency due to one line of code.

**Comment by h-arlt** [comment]
Totally right.
