### ISSUE TITLE
Open a HTML snippet with WebDriver

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#133]
Implement a function to open a HTML snippet using the current WebDriver.

**Comment by occupant23** [comment]
@oomelianchuk Please recheck.

**Comment by h-arlt** [comment]
Please note that I've added a comment to your commit.

**Comment by occupant23** [comment]
@h-arlt Please recheck.

**Comment by h-arlt** [comment]
Looks goods to me and works like a charm.

**Comment by occupant23** [comment]
documentation done
