### ISSUE TITLE
Document test execution order

### ISSUE THREAD

**Issue by h-arlt** [Xceptance/neodymium-library#134]
The JUnit runner used by Neodymium executes the tests in a specific and fix order.
This fact and what execution order is used in detail are not document anywhere.

Also, we need to determine the effect of annotating a test class with `@FixMethodOrder` as described [here](https://github.com/junit-team/junit4/wiki/Test-execution-order#test-execution-order). 
In case there is no effect, fine. But that is something the user should be aware of.
On the other hand, if the annotation has an effect on the test execution order, the user should be aware of that fact too.

**Comment by occupant23** [comment]
Added a new documentation page for JUnit within the develop branch.

**Comment by occupant23** [comment]
@h-arlt Please check if this suits your need.

**Comment by occupant23** [comment]
@rkl-xc Please also recheck it.

**Comment by h-arlt** [comment]
Some remarks:
* IMO page title is too specific; what about to use 'Test Execution' instead?
* > For Neodymium this results in a mixture of ordered and unordered.

  An example would be nice, e.g. two methods (`testA` and `testB`) that are to be run with 3 data sets and two browsers.

Q1: Does Neodymium's test multiplication apply **after** JUnit's method ordering or **before**?
Q2: When using one of JUnit's method sorters that work on the test method's name, has the method's data set (or browser) any impact on the execution order?

**Comment by occupant23** [comment]
added more information and extended the example like recommended

**Comment by h-arlt** [comment]
Looks good to me.

**Comment by rkl-xc** [comment]
review done, added some suggestions, please have a look at it again
