### ISSUE TITLE
Print a one line Neodymium version information at runtime

### ISSUE THREAD

**Issue by rkl-xc** [Xceptance/neodymium-library#139]
Would be helpful to see the running Neodymium version once per launch to verify which neodymium-library is in use. I'd expect to see a line in the stdout saying:

[INFO] Running Xceptance Neodymium Library 4.0.0, see also <https://github.com/Xceptance/neodymium-library>

**Comment by occupant23** [comment]
Logging will be don when instancing the `NeodymiumRunner` or the `NeodymiumCucumberRunner`.
Logging level is info as proposed.

Added a function `Neodymium.getNeodymiumVersion()` to retrieve the version for any reason needed.

**Comment by occupant23** [comment]
documentation done

**Comment by oomelianchuk** [comment]
IMO the changes are good, I have nothing to complain about

**Comment by rkl-xc** [comment]
I'd suppose to improve the version info output "Running a test using Neodymium Library" to transport some more information about the supplier (us) and the software itself. This could be:

Copyright (c) 2018, 2020, Xceptance Software Technologies GmbH, Germany
Neodymium Library <version>, <release date>, MIT License
Open Source best practice test automation library for Web applications
www.xceptance.com, github.com/Xceptance/neodymium-library

This seems to be very long, but it is more professional, than what is currently implemented.

**Comment by h-arlt** [comment]
> I'd suppose to improve the version info output "Running a test using Neodymium Library" to transport some more information about the supplier (us) and the software itself. This could be:
> 
> Copyright (c) 2018, 2020, Xceptance Software Technologies GmbH, Germany
> Neodymium Library <version>, <release date>, MIT License
> Open Source best practice test automation library for Web applications
> [www.xceptance.com](http://www.xceptance.com), github.com/Xceptance/neodymium-library
> 
> This seems to be very long, but it is more professional, than what is currently implemented.

According to the subject of this issue - and as long as this information is printed to the execution log -  we should restrict it to a single line. Otherwise, analysing the logs in a automatic fashion might become tedious as most logging processors are line-oriented.

**Comment by occupant23** [comment]
I adapted the wording a little to:
`This test uses Neodymium Library (version: ?.?.?), MIT License, more details on https://github.com/Xceptance/neodymium-library`

**Comment by wurzelkuchen** [comment]
This is currently spamming the log a bit. 
Three changes needed
a) only print it once, not for every test class
b) give it a toggle in the config
c) add it to the allure report environment
