### ISSUE TITLE
Add Howto Run Neodymium wiki page

### ISSUE THREAD

**Issue by rkl-xc** [Xceptance/neodymium-library#140]
A How to Run Neodymium should be added to the Neodymium Wiki pages as a new How-to page. It should cover the several ways to run Neodymium test ware including the necessary software setup.

**Comment by rkl-xc** [comment]
- documentation added at branch #140-rkl-howto-run-neodymium for review
- the new page is not referenced somewhere, let's see where it can be linked from

**Comment by occupant23** [comment]
@h-arlt please have a first look at it.

**Comment by occupant23** [comment]
@rkl-xc I will add a link on the main(home) wiki page

**Comment by rkl-xc** [comment]
@h-arlt , @ckeiner Please review Basic-Setup-and-Run.md at branch #140-rkl-howto-run-neodymium. Thanks

**Comment by h-arlt** [comment]
@rkl-xc @occupant23 Document reviewed. Please recheck.

**Comment by occupant23** [comment]
done
