### ISSUE TITLE
Add check for test data key exists

### ISSUE THREAD

**Issue by rkl-xc** [Xceptance/neodymium-library#141]
For data driven automated tests it would be useful to have a DataUtils.exist("key") like method, that checks whether a key is defined in the dataset or not. As a workaround this works with Neodymium-4.0.0: while (DataUtils.asString("key", null) != null) { do stuff }

**Comment by occupant23** [comment]
Code and documentation are ready for test.

**Comment by oomelianchuk** [comment]
IMO the changes are good, I have nothing to complain about
