### ISSUE TITLE
Improve SelenideAddons.wrapAssertionError

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-library#142]
The aim of the SelenideAddons.wrapAssertionError is to make JUnit assertion to be alike the Selenide assertions. This is currently not completely fulfilled, as Selenide assertions supply the Allure report with a screenshot and code snippet, which causes the failure (as you can see in [this report](https://github.com/Xceptance/neodymium-library/files/5267281/single-selenide-error.zip)), but the wrapped assertions only take a screenshot ([example](https://github.com/Xceptance/neodymium-library/files/5267287/single-wrapped-assertion.zip)).

This wouldn't be such a problem if the error message from after hook didn't overwrite the one from the test. Such a report with [selenide assertion](https://github.com/Xceptance/neodymium-library/files/5267299/selenide-error-with-after.zip) even if makes it a bit more difficult to figure out the failure reason by not supplying the stack trace, but at least leaves some hints in form of code snippet in the step annotation. The [wrapped assertion](https://github.com/Xceptance/neodymium-library/files/5267339/wrapped-assertion-with-after.zip) instead doesn't have any own step annotation, which makes it difficult to figure out the failure reason, especially if the assertion was made about something, which doesn't have an impact on the currently opened page (makes screenshot irrelevant) 

Please improve the SelenideAddons.wrapAssertionError method by making it to add the failure message to the Allure report. The method could be even better if the stack trace could also be attached to the Allure report, so if there is an option to do it, please also add this functionality.

**Comment by oomelianchuk** [comment]
The issue can probably be fixed by replacing the `SelenideLogger.commitStep(new SelenideLog("Assertion error", message), e);` in the `SelenideAddons.wrapAssertionError`  with the `SelenideLogger.commitStep(SelenideLogger.beginStep("Assertion error", message), e);`  Can we also attach stack trace to `message` here?

**Comment by occupant23** [comment]
@oomelianchuk: adjusted the method. please review

**Comment by oomelianchuk** [comment]
Wonderful! Now the allure report with wrapped asserts looks like [this](https://github.com/Xceptance/neodymium-library/files/5341531/allure-report-with-wrapped-asserts.zip). Thanks
