### ISSUE TITLE
Fix displaying of ignore reasons for test methods in allure report

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-library#145]
There is an option to add a description to` org.junit.@Ignore` to make Allure display a reason for test ignorance, like this:
`@Ignore("not implemented yet")`/`@Ignore("it's possible to add property with missing key")`

so that allure report looks like this for the class:
![ignore_allure_class](https://user-images.githubusercontent.com/34157816/94799179-05851780-03e3-11eb-99bf-629159f10cc0.png)

and for the method:
![ignore_allure_test](https://user-images.githubusercontent.com/34157816/94799273-29485d80-03e3-11eb-9b65-209fc323e22e.png)

Currently, this works only for class level and a test method annotated in the named above way will still be displayed as:
![ignore_allure_test_without_reason](https://user-images.githubusercontent.com/34157816/94799603-aa9ff000-03e3-11eb-8a89-c3461ff45635.png)

This behavior can be caused by overriding the `describeChild` method of `BlockJUnit4ClassRunner` in the `NeodymiumRunner`. The method from Neodymium doesn't pass test method annotations to the description, which makes it impossible for allure to figure out the ignorance reason.

**Comment by oomelianchuk** [comment]
To issue can probaply be fixed by editing the `describeChild` method to match following code:

```
    @Override
    protected Description describeChild(FrameworkMethod method)
    {
        return childDescriptions.computeIfAbsent(method, (m) -> {
            return Description.createTestDescription(getTestClass().getJavaClass(), m.getName(), method.getAnnotations());
        });
    }
```

**Comment by occupant23** [comment]
added the fix

**Comment by occupant23** [comment]
@oomelianchuk and @h-arlt : Can be recheck.

**Comment by h-arlt** [comment]
Works as desired.
