### ISSUE TITLE
Deprecate SelenideAddons.matchAttribute

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#146]
Deprecate the SelenideAddons.matchAttribute function since com.codeborne.selenide.Condition.attributeMatching does a similar job.

**Comment by occupant23** [comment]
Ready to recheck. I also exchanged an example function in the wiki to showcase another supported function instead.

**Comment by h-arlt** [comment]
Please see my comments on your commit.

**Comment by h-arlt** [comment]
Looks good to me.
