### ISSUE TITLE
Create a function to stabilize test that are flaky due to page features that are not relevant for the test

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#148]
I noticed, that the code like this
```
        try
        {
            $("#onetrust-accept-btn-handler").shouldBe(visible);
        }
        catch (ElementNotFound e)
        {
            overlayIsVisible = false;
        }
```
is/can be used in multiple projects, e.g. I built a custom method like this for a customer project. Wouldn't it be a good idea to extend SelenideAddons with methods to wait until or while some condition, without any exception throwing but just returning a boolean value as information whether the condition was fulfilled?

_Originally posted by @oomelianchuk in https://github.com/Xceptance/neodymium-library/issue_comments/703550134_

**Comment by occupant23** [comment]
@georgkunze Have you already added documentation regarding this feature to our wiki dev branch?

**Comment by georgkunze** [comment]
> @georgkunze Have you already added documentation regarding this feature to our wiki dev branch?

I just checked. And there is no added documentatio for this feature.

**Comment by occupant23** [comment]
Documentation needs to be added, Issue is ready  for final test

**Comment by AJakobi** [comment]
Added docu, ready for review
