### ISSUE TITLE
Test suite usage

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#150]
Test and document how/if the TestSuites approach is supported bey Neodymium.
https://github.com/junit-team/junit4/wiki/Aggregating-tests-in-suites

**Comment by oomelianchuk** [comment]
The approach was tested on the [neodymium-example](https://github.com/Xceptance/neodymium-example) project and the code, structured in this way you can find in the [150-split-tests-into-test-suites](https://github.com/Xceptance/neodymium-example/tree/150-split-tests-into-test-suites) branch. As you can see, the Neodymium library allows tests to be aggregated in suites, which can even be parallelized. The parallelization of tests inside the suites is however not possible, which can increase the execution time. While using this approach, you should pay attention to the fact that the tests, included in the suite can still be executed separately. So, if you don’t want to execute the test twice, you should avoid executing the test itself (e.g. by excluding it from the surefire path). Tests can also be included in multiple suites (in the example `AddToCartTest` is included in the `BrowsingTestSuite` and `OrderTestSuite`)

The projection of the test aggregation into allure report is not supported. This also means, that in case, when a test is included in the multiple suites, the results of the test will only be displayed once in the allure report.
[Here](https://github.com/Xceptance/neodymium-library/files/5516707/allure-report-with-suites.zip) you can see, how allure report for such aggregation look like (no difference to simple allure report)

**Comment by occupant23** [comment]
@oomelianchuk Thanks for rechecking. 

Follow up task: Update https://github.com/Xceptance/neodymium-library/wiki/JUnit with the rechecked information. Since this is a way to configure the running order of tests classes.

**Comment by oomelianchuk** [comment]
Documentation added in develop

**Comment by occupant23** [comment]
@georgkunze: Please review @oomelianchuk adjustments in the documentation.

**Comment by occupant23** [comment]
@georgkunze: Please review @oomelianchuk adjustments in the documentation.

**Comment by georgkunze** [comment]
@occupant23 Reviewed the Documentation done in the JUnit part. Seems fine to me.
