### ISSUE TITLE
Support JUnit5

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#151]
Have a look what it would take to support JUnit5. 

It would be nice to support both versions in parallel.
Maybe it could be interesting to come up with some kind of adapter setup that could make it easy to support TestNG.

**Comment by mk-94** [comment]
Hi, i would take it and try to implemet junit 5 Support. Is there anything to look at? How i can start with this issue?

**Comment by occupant23** [comment]
Hi @mk-94, this sounds good. Just fork the project and give it a try.

You should start with the `NeodymiumRunner` which extends `BlockJUnit4ClassRunner`. Afterwards you would've to work on the Statements for TestData, Browser and Parameter. In general, I guess we need to touch nearly everything within the `neodymium.module` package and the belonging sub packages. Most of the functional logic can be reused but needs to be adapted to the JUnit5 standard.

At the moment I not sure if we keep the JUnit4 support for some time so it would be nice if you create a package with similar classes for JUnit5.

Feel free to show your intermediate results or ask questions. I will try to give guidance where I can. 😄 

Thanks for your support!

**Comment by mk-94** [comment]
Thank you. :) I will start today. :)

**Comment by occupant23** [comment]
Reminder link to the forked repo: https://github.com/mk-94/neodymium-library

**Comment by occupant23** [comment]
Hi @mk-94,
I just wanted to ask if you made any progress with the topic and if we can give you some guidance?

**Comment by AJakobi** [comment]
idea for documentation:
comparison of diffs between 4 & 5
