### ISSUE TITLE
Random Browser annotation

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#154]
It would be nice to have an annotation that selects one or more browsers out of all available (to the test case attached) browsers.

e.G.: 
```
@Retention(RUNTIME)
@Target({
  TYPE, METHOD
})
public @interface RandomBrowser()
{
    int value() default 1;
}
```
`value = 1` would mean choose one browser randomly.
If the more browsers than available should be picked randomly an exception should be raised.

**Comment by oomelianchuk** [comment]
Implementation suggestion in [PR!167](https://github.com/Xceptance/neodymium-library/pull/167)

**Comment by occupant23** [comment]
@georgkunze: Please test this feature and check the documentation (should be available in the wikis dev branch).

**Comment by georgkunze** [comment]
@occupant23 Test done. Checked also the documentation

**Comment by georgkunze** [comment]
Checked everything again.

**Comment by georgkunze** [comment]
closed

**Comment by georgkunze** [comment]
Checked everything again and closed
