### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#156]
Update README and try to avoid fixed version numbers.

**Comment by occupant23** [comment]
@georgkunze Please review the changes made by @ufjena.

**Comment by occupant23** [comment]
@oomelianchuk Please review the changes made by @ufjena.

**Comment by oomelianchuk** [comment]
I think the changes in README are fine. They inform people about the showcase project, which is great. I also haven't found any typos or mistakes. To sightly improve the style we might want to split this sentence 

> Neodymium Showcase: This repository contains different showcases and each of them demonstrates and comments on the usage of a single feature of Neodymium

into two, like this:

> Neodymium Showcase: This repository contains different showcases. Each of them demonstrates and comments on the usage of a single feature of Neodymium

This is just a suggestion, please feel free to reject it.

**Comment by occupant23** [comment]
@oomelianchuk: Please go on and adjust this within the development branch.

**Comment by wurzelkuchen** [comment]
We need updates for the 5.0.0 release in the read.me as well
