### ISSUE TITLE
Research jdocs

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#160]
Please research the following library with the focus of using it within Neodymium:
https://github.com/americanexpress/unify-jdocs

Currently we utilize GSON and POJOs within our DataUtils functionalities. See our docu: https://github.com/Xceptance/neodymium-library/wiki/Test-data-provider

Implement more complex object (similar to our internal tests: https://github.com/Xceptance/neodymium-library/blob/master/src/test/java/com/xceptance/neodymium/testclasses/datautils/DataUtilsTests.java) with both approaches and compare their usability.

Please also check how the library is supported by its developers.

Prepare a presentation and a test repo within our internal space.

**Comment by rkl-xc** [comment]
- research done
- sample implemented
- presentation ready
- saved at Gitlab

**Comment by occupant23** [comment]
@rkl-xc 👍 
Issue is done
