### ISSUE TITLE
Research video recording

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#162]
Try to find a a solution to record a video while executing a test automation.

- [ ] Give a overview of possible libraries (Java or JS if injected into the DOM) 
- [ ] Sort them in regards to functionality, support and quality
- [ ] Estimate/plan the integration into Neodymium
- [ ] Implement a short demo if feasible  

https://github.com/Pernosco/DOMRec

**Comment by wurzelkuchen** [comment]
@AJakobi please have a look at the documentation.

**Comment by AJakobi** [comment]
updated docu...pls decide the headings
