### ISSUE TITLE
Prepare a Browserstack test case

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#163]
Contact @occupant23 to get the credentials.
Contact @h-arlt to setup the credentials as secrets within our build/release routine.

Create a basic test case to validate, that our browser stack integration works as expected.
- open a Safari browser within the BrowserStack environment
- visit the Xceptance home page
- validate some basic things (similar to https://github.com/Xceptance/neodymium-template/blob/master/src/test/java/template/neodymium/tests/smoke/HomePageTest.java) but without page objects, test data and changes in the general settings (if possible)

**Comment by occupant23** [comment]
@oomelianchuk I just merged this into development, this should create an error on our test environment. Please validate that this happens due to the not configured credentials and change the instance setup accordingly.

**Comment by oomelianchuk** [comment]
Done, the build is back to stable
