### ISSUE TITLE
Update dependencies as far as possible

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#165]

**Comment by occupant23** [comment]
Updated:
Allure
Cucumber
Selenide
BrowserUp
log4j
jsonPath

**Comment by occupant23** [comment]
Selenide deprecates the `waitUntil` / `waitWhile` functions. Future test cases with the need for a special waiting time should use. `should(Condition, Duration)`. Therefore we need to adjust the example project accordingly.

**Comment by oomelianchuk** [comment]
In case we want to update both allure and cucumber dependencies without having a version conflict, we can use [this](https://www.baeldung.com/maven-version-collision) instructions to do so. In this case, the allure-cucumber dependency would look like the following:
```xml
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-cucumber6-jvm</artifactId>
			<version>${allure.version}</version>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-junit</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>messages</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>create-meta</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>allure-cucumber6-jvm</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>gherkin</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by wurzelkuchen** [comment]
We should do this upfront the next big release. 
Also as a general note there are already new Selenide Updates, which unfortunately removed some deprecated classes.
