### ISSUE TITLE
"After" step visible in Allure report

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#17]
The shutdown/after steps should not necessarily visible in Allure report.
see https://github.com/allure-framework/allure-java/issues/190

Example:
![chrome_2018-01-29_16-16-04](https://user-images.githubusercontent.com/16191117/35519095-9458ad0e-0513-11e8-9ceb-75438f546502.png)

**Comment by marcuskaufmann** [comment]
The allure-java issue is still open. We cannot do anything about it but fork and fix it by our self.

**Comment by occupant23** [comment]
Seems to be fixed, now all After steps are merged into a "Tear down" collapsable.

Works for me
