### ISSUE TITLE
Verify if the configured locale matches a given list of locales

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#171]
Add a function to verify if the current configured locale matches one from a given list of locales.
Build the function analog to `Neodymium.isSite(String... sites)` a function that checks the locale.

Function signature should look like this: 
`Neodymium.isLocale(String... locales)`

**Comment by occupant23** [comment]
@georgkunze: Please create a separate branch(from dev) for this. Please add unit tests similar to the ones for `isSite`.

**Comment by occupant23** [comment]
@georgkunze Please add/adjust the documentation for this feature and add a comment here wehen done.

**Comment by georgkunze** [comment]
@occupant23 documentation is done in the isLocale branch of the wiki.

**Comment by georgkunze** [comment]
@wurzelkuchen Please review
