### ISSUE TITLE
Remove visual assert test functionality

### ISSUE THREAD

**Issue by ufjena** [Xceptance/neodymium-library#182]
Check all neodymium projects.
Remove existing test cases that use visual assert.

Is associated with #11 and #89

**Comment by ufjena** [comment]
Check all nedodymium projects.
Remove existing test cases that use visual assert.

**Comment by georgkunze** [comment]
Removed code and Documentation

**Comment by wurzelkuchen** [comment]
The visualassertion.properties is still there, needs to be removed.
