### ISSUE TITLE
Discover and document usage of @Category in JUnit

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-library#183]
JUnit `Category` annotation is, analog to `Suite`, a feature for test grouping. Please, discover and describe in the documentation, how to use this annotation and in which cases.

**Comment by oomelianchuk** [comment]
Done

**Comment by wurzelkuchen** [comment]
@georgkunze please recheck in develop (documentation)

**Comment by georgkunze** [comment]
Recheck done. Is Fine! Closed
