### ISSUE TITLE
Support passing preferences into browser configurations

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-library#192]
Similar to options and capabilities, browser preferences allow configuring many useful things. Users may take advantage of disabling some dialogs, which are not accessible for automation or pre-setting default values. 

While options and capabilities define, what features should current browser session use, the preferences define global browser settings e.g. home page, alerts permission, default folders, etc. 

Currently, the preferences are only supported by Chrome and Firefox. Think about the introduction of the `preferences`  option for these browsers.

**Comment by AJakobi** [comment]
Documentation done....assigned to @wurzelkuchen to recheck
