### ISSUE TITLE
Update test data documentation 

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#199]
Add the following:

* How and where to create a test data file. (Should include infos about matching path)
* How and where to create a package test data file. (Should include infos about accessibility if moved in the structure )
* Hint that the order of the data file reader could lead to problems if you have `FooTest.csv` and  `FooTest.json`

**Comment by oomelianchuk** [comment]
Please see the  #199-update-test-data-documentaion in the neodymium-library.wiki project
