### ISSUE TITLE
Remove support for Opera and PhantomJS

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-library#200]
As far as I understand, there is already no special handling for Opera and PhantomJS driver setup. Nevertheless, the `NeodymiumConfigutation` still contains methods to configure driver paths for those browsers. 

According to the [Selenium 4 release notes ](https://www.selenium.dev/selenium/docs/api/javascript/page/Changes.html), the support for these browsers will be completely removed. 

We should think about removing `getPhantomJsDriverPath()` and `getOperaDriverPath()` methods from the `NeodymiumConfigutation` class and clean up the code.

**Comment by wurzelkuchen** [comment]
This was this was done during the selenide update.
