### ISSUE TITLE
Upgrade to Selenium 4 / Selenide 6

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-library#203]
Since on October 13, 2021, Selenium 4.0 was officially released we can think about upgrading to this version. Currently, the latest Selenide version that supports the Selenium 4 is 6.1.1, so the first thing that we need to do is to update Selenide dependency to this version.

The first problem we'll face is a proxy for connection with Selenium Grid. To enable this proxy setting we used to create a custom HttpCommandExecutor instance, which used a custom HttpClient for the communication. To construct the suitable HttpClient we used to create an OkHttpClient, which contained the proxy settings and then wrap it in the OkHttpClient object offered by Selenium. This mechanism is no longer supported by Selenium. Instead, there are two HttpClient's offered: NettyClient and TracedHttpClient. Both of these classes are closed for extensions, that's why we would need to create our own implementation of HttpClient and HttpClient.Factory and define the communications.

**Comment by oomelianchuk** [comment]
On update consider the following issue https://github.com/SeleniumHQ/selenium/issues/10974. This may provoke issues with browser driver port collision on Linux.

**Comment by wurzelkuchen** [comment]
@AJakobi please check what changes in the documentation are needed, and update the documentation accordingly. In doubt talk to @oomelianchuk

**Comment by AJakobi** [comment]
Documentation done....assigned to @wurzelkuchen to recheck
