### ISSUE TITLE
Jenkins, Gitlab or other CI/CD

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/neodymium-library#21]
Setup and document how to use Jenkins with Neo as well as how to use GitLab with Neo. Especially important is build and reporting. 

* How to configure build
* How to use parallel execution
* How to access the report
* How to do historical reporting

**Comment by marcuskaufmann** [comment]
https://github.com/Xceptance/neodymium-library/wiki/Setup-continuous-tests-with-Jenkins
