### ISSUE TITLE
BrowserOptions set via arguments are getting ignored on SeleniumGrid

### ISSUE THREAD

**Issue by Ankit3794** [Xceptance/neodymium-library#224]
**Scenario:-** wants to run chrome instance with `--disable-dev-shm-usage` option on selenium grid. Passed it as argument in browser.properties

browser.properties
```
browserprofile.Chrome.name = Chrome
browserprofile.Chrome.browser = chrome
browserprofile.Chrome.testEnvironment = grid
browserprofile.Chrome.arguments = disable-dev-shm-usage
```
credentials.properties
```
browserprofile.testEnvironment.grid.url = http://localhost:4444/
browserprofile.testEnvironment.grid.username =
browserprofile.testEnvironment.grid.password =
```

seems like, arguments passed from browserprofie.<tagName>.arguments are only being passed as Options if testEnvironment is empty or local. 

Is there any way to pass arguments in TestEnvironment (i.e., Selenium Grid) approach.

**Comment by wurzelkuchen** [comment]
Hi, thanks for reaching out to us. 
I'll have a look and let you know once I checked the scenario.

Best,
Bernd

**Comment by wurzelkuchen** [comment]
Hi, 

unfortunately, this seems to be a [Selenium issue](https://github.com/SeleniumHQ/selenium/issues/7084). Currently Neodymium is still based on Selenium 3.x while this bug, seems to be fixed in Selenium 4.x.
We are working on an update to Selenium 4.x but it still requires some work.

Best,
Bernd

**Comment by wurzelkuchen** [comment]
Hi,

it took much longer than we anticipated, but with our current release for Neo 5.0.0. we support Selenide 7 which, comes with Selenium 4 and therefore, this issue should be resolved.

Best,
Bernd
