### ISSUE TITLE
Keep browser open on failure

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#24]
Similar to the keep browser open feature but only if the test has failed

**Comment by occupant23** [comment]
Please add a setting to en/disable this feature. (Default=disabled)
Please add documentation for this feature.

Issue:
If you run a test with multiple DataSet the/a Browser should stay open for each failed execution while the the other tests are continued.
At the moment the complete test is stopped when the first error happens.

**Comment by occupant23** [comment]
Can we also make this work for Cucumber?
If not please adjust documentation accordingly.

**Comment by occupant23** [comment]
Rechecked this feature after changes to the implementation. Works as expected. 
Please add documentation for this feature.
