### ISSUE TITLE
Add headless browser feature

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#26]
Expand browser properties to support headless mode for different browser.

**Comment by occupant23** [comment]
The headless mode should ignore the keepBrowserOpenOnFailure feature, since there is no point in having an invisible browser. This just leads to zombie webDriver processes.

**Comment by occupant23** [comment]
rechecked feature for cucumber and java, works as expected,
also checked, that it doesn't interfere with chrome profiles.

Just one thing
I would change the signature of 
        Driver.tearDown(scenario.isFailed());
to 
        Driver.tearDown(scenario);
and add JavaDoc to the function and explain that the Scenario can just be added to the calling function via dependency injection

**Comment by occupant23** [comment]
done and rechecked

**Comment by occupant23** [comment]
Rechecked after implementation changes.
