### ISSUE TITLE
Selenide timeout settings

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#27]
Set timeouts in Selenide configuration class for both Java and Cucumber tests. Since most Selenide functions are affected from this timeout the configuration should be set immediately after driver is built.

```Java
Configuration.timeout = Context.get().configuration.timeout();
Configuration.collectionsTimeout = Configuration.timeout * 2;
```

**Comment by occupant23** [comment]
rechecked for Java and Cucumber, works as expected

**Comment by occupant23** [comment]
needs to be rechecked due to refactoring

**Comment by occupant23** [comment]
rechecked after changes in implementation
