### ISSUE TITLE
Property files for data sets

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#28]
At the moment we can not support property files as source for data sets. Its the nature of properties that data is flat. We need to decide whether we define a key format that allows to define multiple data sets or we drop support properties for data set and use e.g. yaml instead

Thoughts on key format:
```
0.<Key> = <Value>
1. ...

properties for first iteration
<Key> = <Value>   ===   0.<Key> = <Value>  

how to handle the gap?
0.<Key>
2.<Key>

special case
<Key>
2.<Key>
```

**Comment by occupant23** [comment]
Added clarification for supported file format to the current TestData documentation.

We won't implement this feature since it would not be used if you have easier and more compelling formats at hand.
