### ISSUE TITLE
Element highlighting

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#30]
For debugging/test creation purpose it would be nice to have the elements that are currently selected by Selenide would be highlighted in the browser, so the user can visually track what the test is doing.

Maybe use this lib: https://github.com/kamranahmedse/driver.js

**Comment by marcuskaufmann** [comment]
We shouldn't use "window.NEO" as namespace for our stuff, because the relationship to neodymium is not visible. Same for style classes e.g. "neo-outline-box".

**Comment by occupant23** [comment]
changed naming from neo to neodymium to clarify connection

**Comment by marcuskaufmann** [comment]
Highlighting doesn't work unless an implicit wait time is defined. We might need to imply an implicit wait time if highlighting is used but no implicit wait time was explicit set.

**Comment by marcuskaufmann** [comment]
Highlighting also doesn't work for drop down (select tag). Are we able to distinguish the elements and use a very custom highlighting for these drop down menus?

**Comment by occupant23** [comment]
fixed the bug that highlighting did not work in frames or on window switch and added test for it,
added a short highlight time if somebody only activates highlighting

**Comment by marcuskaufmann** [comment]
Works like a charm
