### ISSUE TITLE
Improve localization feature

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#33]
Change localization feature so it will accept any locale (even invalid locales) as key and will simply look up the yaml file. Only if it couldn't be found then use the apache localization tool as backup. Also adjust documentation in wiki

**Comment by marcuskaufmann** [comment]
Changed the behavior to lookup with the given locale no matter if it is correct or not. If it couldn't be found then the backup depends on the given locale. If the given locale is a correct locale like 'en_US' the fallback would look for keys starting with 'en'. If it isn't a correct locale then fallback path would look for keys starting with 'default'

**Comment by occupant23** [comment]
works for me
