### ISSUE TITLE
Update Selenide

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#35]
Update Selenide dependency to a newer version. There are some issues with this task as dependencies change too. For instance GSON is now runtime only dependency but we need it to have it at compile time. Same issue for Apache-Commons library. Furthermore Selenium changed internally from Apache-HTTP to OkHTTP which raises more structural issues to solve.

**Comment by marcuskaufmann** [comment]
updated to 4.12.1

**Comment by marcuskaufmann** [comment]
reopened because we want to close this issue first after we have released

**Comment by marcuskaufmann** [comment]
Since Selenide released a bugfix release today I changed this dependency from 4.12.1 to 4.12.2

**Comment by occupant23** [comment]
nothing broke and dependency is visible, seems to work
