### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#40]
Make the project ready for maven central

https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by marcuskaufmann** [comment]
com.xceptance is now reserved with [resolving](https://issues.sonatype.org/browse/OSSRH-40806)
We are asked to comment the ticket after the next release.

**Comment by occupant23** [comment]
added a profile to pom.xml to enable signing the artifacts only when needed 

switches
- "-P release-neodymium" to use in release CI job of the master branch 
- "-D signArtifacts=true" triggers the same profile to use in the development CI job (should take away concerns with the name of the profile)

**Comment by marcuskaufmann** [comment]
The artifacts are published an accessible through https://oss.sonatype.org/content/groups/public/com/xceptance/neodymium-library/

As of the moment the version can not be found via search.maven.com but this should change in the next hours. Their workflow to publish has finished without any errors so it shoud be a matter of time until it can be found.
