### ISSUE TITLE
Update javadoc to 3.0.1

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#43]
Update javadoc to 3.0.1 when available and remove hotfix for Java 10.

See https://issues.apache.org/jira/browse/MJAVADOC-517
See https://issues.apache.org/jira/browse/LANG-1365

**Comment by occupant23** [comment]
done, can be rechecked

**Comment by marcuskaufmann** [comment]
rechecked for openjdk 10.0.2+13 and oracle jdk 10+44
