### ISSUE TITLE
Update Cucumber to 4.x

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#48]
Update Cucumber version to 3.x once the allure support >= version 2.8 is available.

See the link for latest release: https://github.com/allure-framework/allure2/releases

Remove  "io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm" if the update above is successful.

**Comment by occupant23** [comment]
Allure is released by now: https://github.com/allure-framework/allure2/releases/tag/2.8.0

**Comment by occupant23** [comment]
Try to update Cucumber to 4.x.x when possible.

**Comment by occupant23** [comment]
updated Allure to 2.8.1
updated Cucumber to 4.2.0

adjusted and ran example projects to analyze differences and detect errors

**Comment by jowerner** [comment]
Allure 2.9.0 is available now. However, not sure if we can safely update.

**Comment by occupant23** [comment]
Will try to update Allure to 2.9.0. Updating Cucumber to 4.x won't be possible since  Allure is bound to 3.x. . Added a new ticke for this #75.

**Comment by occupant23** [comment]
updated cucumber to 4.2.3
