### ISSUE TITLE
support getting localization for a given locale

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#65]
We should add another sugar method to the Neodymium context in order to retrieve a translation for a key in a given locale in order if a user does not want to uses the global context or just has the need for a special language in rare case e.g. checking certain wordings before changing the language.

**Comment by occupant23** [comment]
documentation for the new should be added to the wiki.

implementation done, ready to test

**Comment by jowerner** [comment]
Looks like the look-up fallback is not quite right. Assume the default locale is set to "en_US". When I try to look up a localized text using locale parameter "fr_FR", the outcome might be unexpected.

Expected fallback: "fr_FR" -> "fr" -> "default"
Actual fallback: "fr_FR" -> "en" -> "default"

**Comment by jowerner** [comment]
Please add some javadoc to NeodymiumLocalization.getText(String, String) and show-case the use of this method in the wiki.

**Comment by occupant23** [comment]
fixed the bug and added documentation for this feature
