### ISSUE TITLE
fastSetValue and clickViaJs can not be set in neodymium.properties

### ISSUE THREAD

**Issue by rklehm-xc** [Xceptance/neodymium-library#67]
Neodymium.fastSetValue(true); as well as Neodymium.clickViaJs(true); can be set at runtime only. It might be a good idea to set them for the whole test suite at neodymium.properties.

**Comment by occupant23** [comment]
added documentation

**Comment by jowerner** [comment]
Now that these two settings are official properties, they should be documented on the Configuration wiki page.

**Comment by jowerner** [comment]
Please ignore my comment. They are there already.
