### ISSUE TITLE
Using YAML reserved keywords in localization file causes an initialization error 

### ISSUE THREAD

**Issue by rklehm-xc** [Xceptance/neodymium-library#68]
Using e.g. Yes: Ja; in the localization.yaml causes a test run to stop with an initialization error, that is currently not closer specified to the test developer. A solution might be to be to provide more feedback when occurred or to avoid this error in the means of localization.

**Comment by occupant23** [comment]
Analyzed this problem and found it is hard to find a good solution for all auto conversions, that could happen in YAML.

So we decided to implement the proposed solution. When such errors occur we catch them and throw a RuntimeException providing the following message to the user: 

> Localization keys must be of type String. (e.g. use "Yes" instead of Yes as key. This is due to YAML auto conversion.

**Comment by jowerner** [comment]
Since the auto-conversion of certain literals to booleans is a common pitfall for YAML beginners, we should add a note to the Localization section in the wiki. Especially, that not only values are affected, but also keys.

**Comment by occupant23** [comment]
added documentation
