### ISSUE TITLE
Add Appium support

### ISSUE THREAD

**Issue by wurzelkuchen** [Xceptance/neodymium-library#71]
For a good coverage of browser based frontend tests, mobile browser support would be great and is requested by a customer of mine. 
There is a way to include appium (which works well with saucelabs). 
See https://github.com/selenide-examples/selenide-appium for further information. This example however seems not to work with the current neodymium version, which is probably due to incompatible versions of selenium and appium.

**Comment by occupant23** [comment]
ready for test

**Comment by wurzelkuchen** [comment]
tested it, works well with saucelabs and android/ios emulators
