### ISSUE TITLE
Support Neodymium build in an Java 11 environment

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#73]
See what needs to be done.

**Comment by occupant23** [comment]
added the following workaround to the pom.xml in order to do this without skipping the java doc for local builds.
```
<configuration>
    <source>8</source>
</configuration>
```
This can be undone when maven-javadoc-plugin v3.1.0 is released since this should fix the issue.
(See here for mor info: https://issues.apache.org/jira/browse/MJAVADOC-555)

**Comment by jowerner** [comment]
Works for me, with and without your modification. I'm using OpenJDK 11.
