### ISSUE TITLE
dev-neodymium does not override neodymium.properties

### ISSUE THREAD

**Issue by rklehm-xc** [Xceptance/neodymium-library#74]
Once I had to set the neodymium.webDriver.chrome.pathToDriverServer (and firefox) at neodymium.properties I expect them to be overridden with the same settings at dev-neodymium.properties in place. But running this the setting from neodymium.properties has been used. I worked around by passing these parameters through the command line switches using -Dneodymium.webDriver.chrome.pathToDriverServer=

**Comment by occupant23** [comment]
fixed the bug, ready for test

**Comment by jowerner** [comment]
The test case (setup) might not work as intended. Two issues here:

* The test case setup creates a file such as "./config/dev-neodymium1145134166378993830" which I believe will never be read. Did you want to create "./config/dev-neodymium.properties" instead?
* The other file "./config/temp-neodymium.properties" will be read, but this file does not really overwrite a setting with a different value so the test case does not prove anything.

**Comment by occupant23** [comment]
rethought tests and fixed the issue
