### ISSUE TITLE
Support for testingbot

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#77]
We want to enable our users to use also testingbot beside saucelabs as a test environment.

**Comment by wurzelkuchen** [comment]
Currently the chorme emulation profiles do not work with testingbot/saucelabs.
The MetaData states that goog:chromeOptions and args are empty.

**Comment by occupant23** [comment]
merged back into develop, ready for test

**Comment by wurzelkuchen** [comment]
rechecked feature
