### ISSUE TITLE
Implement a clean up without parameters

### ISSUE THREAD

**Issue by ckeiner** [Xceptance/neodymium-library#78]
I want to be able to close the browser during a test case. This seems possible for Cucumber, where the `teardown`-method is used to clean up after a scenario was run, thus also expecting a `Scenario` as argument. Yet, I'd like to use such a clean up without using Cucumber. Therefore is it possible you could implement such a `teardown`-method without parameters?

**Comment by occupant23** [comment]
Implemented as WebDriverUtils.tearDown(boolean isFailed) in order to make use of Neodymium's keepBrowserOpenOnFailure feature.

**Comment by occupant23** [comment]
@ckeiner: Ready to test
