### ISSUE TITLE
Logging does not work in child projects

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#80]
Since we activated the logging in the library project it seems that there is a conflict between the logging.properties files.

**Comment by occupant23** [comment]
please see #84 for additional documentation

**Comment by rschwietzke** [comment]
You can not refer to #84 when you refer in #80 to #84... this is an infinite loop. #84 does not have additional documentation.

**Comment by ckeiner** [comment]
TODO:
* Change the name of the log file to something akin to "neodymium_errors.log"
* Add the name of the logger to the default logging settings
* Adapt wiki

**Comment by occupant23** [comment]
documentation added to the development wiki
