### ISSUE TITLE
Improved Test Data Mapping

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/neodymium-library#83]
We suggest to improve the test data mapping from JSON data by mapping into well structured and nested Java objects not just flat POJOs when requested but rather all the time.

The test case could declare something like:

```java
public Test extends AbstractTest
{
    @Data
    private User userData;

    // rest here 
}

public User 
{
    public String name;
    public List<Address> addresses; 
    public CreditCard creditCard;
}
```
```json
{
    "name" : "Mr. Foobar",
    "addresses" : [
        {
            "street" : "10 Foobar",
            "postalCode" : "09181"
    }
    ],
    "creditcard" : {
        "number" : "4111 XXXX XXXX XXXX",
        "expiration" : "07/20"
    }
}
```

**Comment by occupant23** [comment]
I will divide this feature request into two steps. The first part (this issue) will include the improved test data mapping to complex objects. The second part will take care of the suggested annotation.

I removed Jackson and use GSON instead to map/convert Objects from JSON to Java.

**Comment by occupant23** [comment]
added documentation to development wiki

**Comment by h-arlt** [comment]
Please fix JavaDoc for method `DataUtils.get(Class)`:
 * "the inferred class" -> "the inferred type"
 * "A reference to an clazz..." -> "A reference to a class.... and enriched with parsed test data"
