### ISSUE TITLE
Automation with local Safari browser profile does not work

### ISSUE THREAD

**Issue by mgnauck** [Xceptance/neodymium-library#86]
Selecting a local Safari(Driver) browser profile results in a NPE when executing the test. Safari and SafariDriver are available on the path (or, alternatively, paths were provided directly via the properties). Automation with other browsers works on the very same machine and project, as does automation with Safari(Driver) work in other, non-Neodymium projects.

![Safari-Issue](https://user-images.githubusercontent.com/17846097/57129449-b58dc580-6d96-11e9-8998-8491d5c201bf.png)

**Comment by occupant23** [comment]
Added support in Neodymium.
Documentation needed add the following link to document the enabling process.

https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari#2957277

**Comment by occupant23** [comment]
added documentation to the development wiki

**Comment by mgnauck** [comment]
Tested successfully.
