### ISSUE TITLE
Instantiate test data object via an annotation

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#90]
Add an `@Data` annotation to instantiate object with values stemming from the test data.

```Java
public Test extends AbstractTest
{
    @Data
    private User userData;

    // rest here 
}
```

Follow up ticket from #83

**Comment by oomelianchuk** [comment]
it would be good to mention the feature [here](https://github.com/Xceptance/neodymium-library/wiki/Test-data-provider)

**Comment by AJakobi** [comment]
Added to docu, ready for recheck
