### ISSUE TITLE
DataUtils.get(Class<T>) throws JsonSyntaxException

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#93]
DataUtils.get(Class<T>) does not work with simple Strings (containing spaces) on the first level. 
This results in a JsonSyntaxException.

**Comment by h-arlt** [comment]
Changes look good to me.

From a code style perspective, variables should be declared as 'final' unless explicitly needed in order to avoid issues caused by accidental re-assignments.
