### ISSUE TITLE
Improve TestingBot support

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#95]
You can configure the idle timeout for TestingBot. This can be handy in some cases.

See the following link for details:
https://testingbot.com/support/other/test-options#idletimeout

**Comment by jowerner** [comment]
TestingBot provides other configuration options that might come in handy, such as **maxduration** and **selenium-version**, but there may be more. It might be a good idea to support all currently known TestingBot options, as long as they are simple and can be configured easily in a properties file (i.e. no complex objects).

**Comment by occupant23** [comment]
added the recommended switches for SauceLabs and TestingBot

**Comment by jowerner** [comment]
Both SauceLabs and TestingBot document the type of the **max-duration** and **idle-timeout** capabilities to be integers. Neodymium, however, pass them as strings. Looks like TestingBot accepts this nevertheless, but this might change. Haven't tried SauceLabs.

**Comment by occupant23** [comment]
adjusted accordingly
