### ISSUE TITLE
Allow definition of test data file name

### ISSUE THREAD

**Issue by wurzelkuchen** [Xceptance/neodymium-library#96]
Currently test data sets are defined by the name of the java class. E.g. TestCheckout.jjava needs the testdata in a file like TestCheckout.json.

This is forces us to keep testdata, used in different test cases multiple times. A more user friendly approach would be to allow the user, to define his/her own filename.

@DataSet(name="myTestDataFile.json")

**Comment by occupant23** [comment]
implemented it on class level since method level would be very complicated and would result in a higher runtime since the IO datafile operations would have to be called for every test method instead of once per test class.

Documentation need to be done for this.

**Comment by occupant23** [comment]
added documentation in development wiki
